debug: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/northwind
    username: postgres
    password: test

  jpa:
    database: postgresql
    generate-ddl: false
    hibernate.ddl-auto: none

    properties.hibernate.cache.use_second_level_cache: fales
    properties.hibernate.format_sql: true
    properties.hibernate.generate_statistics: true
    properties.hibernate.jdbc.batch_size: 15
    properties.hibernate.order_inserts: true


logging:
  level:
    root: warn
    org.hibernate.SQL: debug
    org.hibernate.type: debug
    org.hibernate.type.descriptor.sql: debug