version: '3.8'

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres12
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'northwind'

    # 存放資料到本地
    volumes:
      - './data:/var/lib/postgresql/data'
      - './northwind.sql:/docker-entrypoint-initdb.d/northwind.sql'